---
rfiles:
  device_startup:
    description: "Template to generate startup configuration for network devices"
    query: "device_startup_info"
    template_repository: "self"
    template_path: "device_startup_config.tpl.j2"

  clab_topology:
    query: "topology_info"
    template_repository: "self"
    template_path: "topology.tpl.j2"